library(shiny)
library(leaflet)
library(ggplot2)
library(choroplethr)
library(RTextTools)
library(stringr)
library(lubridate)
library(tidyr)
library(plyr)
library(dplyr)
library(purrr)
library(twitteR)
library(tidyverse)
library(RCurl)
library(maps)
library(mapdata)
library(grid)
library(RJSONIO)
library(streamR)
library(sp)
library(maptools)
library(ROAuth)
library(MonetDBLite)
library(spatialEco)
library(RColorBrewer)
library(scales)
library(lattice)
library(shinythemes)


ui <- dget("ui.R")

server <- dget("server.R")

shinyApp(ui = ui, server = server)
